### ISSUE TITLE
Idle threads not counted right for older JBoss dumps not using EnhancedQueueExecutor

### ISSUE THREAD

**Issue by aogburn** [aogburn/yatda#20]
It'd have idle threads instead like:
`"default task-96" #277 prio=5 os_prio=0 tid=0x0000000004c18000 nid=0x1b8e1 waiting on condition [0x00007f333dffa000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000005c2e617f0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by aogburn** [comment]
https://github.com/aogburn/yatda/commit/926185a661c4986b43e3f4ad94895f2259143010
